name: React Native CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # allows manual run

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Get code
      - name: Checkout repo
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      # Step 3: Install JS dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Step 4: Run ESLint (linting)
      - name: Run lint
        run: yarn lint

      # Step 5: Run Jest tests
      - name: Run tests
        run: yarn test --ci
